---
base:
    packages: [git, vim, iotop, fail2ban, build-essential, libssl-dev, python-software-properties]
    projectdir: /srv/www/ongr
    timezone: UTC
    locale: en_US.utf8
remote:
    hostname: demo.ongr
    fqdn: demo.ongr.rocks
    extra_hosts: []
    user: nfq
    group: web
nginx:
    remove_default: false
    docroot: /srv/www/ongr/current/web
    servername: demo.ongr.rocks
    index: app.php
    worker_processes: 1
    worker_connections: 1024
    client_body_buffer_size: 8k
    client_max_body_size: 15m
nodejs:
    version: _5.x
    packages: [bower, gulp]
mariadb:
    repo: http://sfo1.mirrors.digitalocean.com/mariadb/repo/10.1/ubuntu
    root_password: root
    database: ongr
    user: ongr
    password: ongr
elasticsearch:
    url: https://download.elastic.co/elasticsearch/elasticsearch/elasticsearch
    version: 2.2.0
    listen_addr: 127.0.0.1
    port: 9200
    cluster_name: ongr-cluster
    node_name: ongr-node
    shards: 1
    replicas: 0
    datapath: /var/lib/elasticsearch/data
    pluginpath: /usr/share/elasticsearch/bin/plugin
    configpath: /etc/elasticsearch/elasticsearch.yml
    plugins: [mobz/elasticsearch-head]
php:
    ppa: ondrej/php
    version: 5.6
    packages: [fpm, cli, intl, mcrypt, curl, gd, common, mysql]
    config:
        fpm:
          syslog_facility: daemon
          syslog_ident: php-fpm
          log_level: notice
          emergency_restart_threshold: 10
          emergency_restart_interval: 60
          process_control_timeout: 10
          process_max: 0
          daemonize: yes
        pool:
          user: nfq
          group: web
          listen_owner: www-data
          listen_group: www-data
          listen_mode: "0660"
          pm: static
          pm_max_children: 10
          pm_start_servers: 1
          pm_min_spare_servers: 1
          pm_max_spare_servers: 4
          pm_process_idle_timeout: 10s
          pm_max_requests: 200
        ini:
          opcache:
            enable: 1
            enable_cli: false
            memory_consumption: 256
            interned_strings_buffer: 8
            max_accelerated_files: 9600
            validate_timestamps: 1
            revalidate_freq: 0
            fast_shutdown: 1
fail2ban:
    ignoreip: 127.0.0.1/8
    bantime: 10800
    findtime: 600
    maxretry: 3
