---
- name: Set the hostname in /etc/hostname
  lineinfile: dest=/etc/hostname line="{{ vagrant_local.hostname }}"
  register: added_hostname

- name: Set the hostname
  shell: hostname {{ vagrant_local.hostname }}
  when: added_hostname == True

- name: Update /etc/hosts
  lineinfile: dest=/etc/hosts regexp='^127\.0\.0\.1' line='127.0.0.1 localhost {{ vagrant_local.hostname }}' owner=root group=root mode=0644

- name: vagrant groups
  user: name=vagrant groups=www-data append=yes

- name: Change vagrant pwd
  lineinfile: dest=/home/vagrant/.bashrc line="cd /var/www/public"

- name: Add vagrant umask
  lineinfile: dest=/home/vagrant/.bashrc line="umask 0002"
